//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char explosion_right [] = {
0x20, 0x44, 0x08, 0x10, 0x06, 0x10, 0x48, 0x24, 
};
