//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char spaceship_right [] = {
0x00, 0x80, 0x80, 0xF8, 0xFC, 0xFC, 0xFC, 0xFC, 
};
