//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

#ifndef _SPRITES
#define _SPRITES_H

const unsigned char invader0 [] = {
0x30, 0x1C, 0x76, 0x3C, 0x3C, 0x76, 0x18, 0x30, 
};



#endif