//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

const unsigned char spaceship[] = {
0x01, 0x03, 0x03, 0x3F, 0x7F, 0x7F, 0x7F, 0x7F, 0x00, 0x80, 0x80, 0xF8, 0xFC, 0xFC, 0xFC, 0xFC, 
};
